-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.about_us (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  en_title text NOT NULL,
  id_title text NOT NULL,
  en_about_content text NOT NULL,
  id_about_content text NOT NULL,
  en_brand_tagline text NOT NULL,
  id_brand_tagline text NOT NULL,
  CONSTRAINT about_us_pkey PRIMARY KEY (id)
);
CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  email text NOT NULL,
  fullname text,
  phone text,
  gender USER-DEFINED,
  domicile jsonb,
  height integer,
  weight integer,
  avatar_url text,
  birthdate date,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.article (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL UNIQUE,
  en_title text NOT NULL,
  id_title text NOT NULL,
  author uuid NOT NULL,
  category ARRAY NOT NULL,
  en_content text NOT NULL,
  id_content text NOT NULL,
  status USER-DEFINED NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT article_pkey PRIMARY KEY (id),
  CONSTRAINT article_author_fkey FOREIGN KEY (author) REFERENCES public.author(id)
);
CREATE TABLE public.article_category (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  udpated_at timestamp with time zone NOT NULL DEFAULT now(),
  en_category text NOT NULL,
  id_category text NOT NULL,
  en_description text,
  id_description text,
  CONSTRAINT article_category_pkey PRIMARY KEY (id)
);
CREATE TABLE public.author (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  jobdesc text NOT NULL,
  slug text NOT NULL UNIQUE,
  CONSTRAINT author_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_activity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  chat_activity_data jsonb NOT NULL,
  public_id uuid,
  user_id uuid,
  CONSTRAINT chat_activity_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consult_schedule (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  fullname text NOT NULL,
  complaint text NOT NULL,
  date_of_birth date NOT NULL,
  height integer NOT NULL,
  weight integer NOT NULL,
  gender USER-DEFINED NOT NULL,
  location jsonb NOT NULL,
  scheduled_date timestamp with time zone NOT NULL,
  scheduled_time time with time zone NOT NULL,
  payment_status USER-DEFINED NOT NULL,
  CONSTRAINT consult_schedule_pkey PRIMARY KEY (id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  en_title text NOT NULL,
  id_title text NOT NULL,
  en_description text NOT NULL,
  id_description text NOT NULL,
  highlight_image text NOT NULL,
  reference_image text,
  organized_image text NOT NULL,
  organized_by text NOT NULL,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  location_name text NOT NULL,
  location_map text,
  status USER-DEFINED NOT NULL,
  CONSTRAINT events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  name text NOT NULL,
  en_description text NOT NULL,
  id_description text NOT NULL,
  location_map text,
  logo text,
  highlight_image text NOT NULL,
  reference_image ARRAY,
  CONSTRAINT hotel_pkey PRIMARY KEY (id)
);
CREATE TABLE public.medical (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  en_title text NOT NULL,
  id_title text NOT NULL,
  en_tagline text NOT NULL,
  id_tagline text NOT NULL,
  highlight_image text NOT NULL,
  reference_image ARRAY,
  duration_by_day integer NOT NULL,
  duration_by_night integer,
  spesific_gender USER-DEFINED NOT NULL,
  en_medical_package_content text NOT NULL,
  id_medical_package_content text NOT NULL,
  included jsonb,
  vendor_id uuid NOT NULL,
  real_price text NOT NULL,
  discount_price text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::status_content,
  CONSTRAINT medical_pkey PRIMARY KEY (id),
  CONSTRAINT medical_list_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendor(id)
);
CREATE TABLE public.medical_equipment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  en_title text NOT NULL,
  id_title text NOT NULL,
  en_description text NOT NULL,
  id_description text NOT NULL,
  spesific_gender USER-DEFINED NOT NULL,
  highlight_image text NOT NULL,
  reference_image ARRAY NOT NULL,
  real_price text NOT NULL,
  discount_price text,
  status USER-DEFINED NOT NULL,
  CONSTRAINT medical_equipment_pkey PRIMARY KEY (id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  en_title text NOT NULL,
  id_title text NOT NULL,
  en_tagline text NOT NULL,
  id_tagline text NOT NULL,
  highlight_image text NOT NULL,
  reference_image ARRAY,
  duration_by_day integer NOT NULL,
  duration_by_night integer,
  spesific_gender USER-DEFINED NOT NULL,
  en_medical_package_content text NOT NULL,
  id_medical_package_content text NOT NULL,
  en_wellness_package_content text NOT NULL,
  id_wellness_package_content text NOT NULL,
  included jsonb,
  vendor_id uuid NOT NULL,
  hotel_id uuid NOT NULL,
  real_price text NOT NULL,
  discount_price text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::status_content,
  CONSTRAINT packages_pkey PRIMARY KEY (id),
  CONSTRAINT packages_list_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendor(id),
  CONSTRAINT packages_list_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.hotel(id)
);
CREATE TABLE public.payment_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  transaction_id text NOT NULL,
  fullname text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  address text NOT NULL,
  payment_status USER-DEFINED NOT NULL,
  packages_id uuid,
  medical_id uuid,
  wellness_id uuid,
  consultation_id uuid,
  medical_equipment_id uuid,
  CONSTRAINT payment_records_pkey PRIMARY KEY (id),
  CONSTRAINT payment_records_packages_id_fkey FOREIGN KEY (packages_id) REFERENCES public.packages(id),
  CONSTRAINT payment_records_medical_id_fkey FOREIGN KEY (medical_id) REFERENCES public.medical(id),
  CONSTRAINT payment_records_wellness_id_fkey FOREIGN KEY (wellness_id) REFERENCES public.wellness(id),
  CONSTRAINT payment_records_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consult_schedule(id),
  CONSTRAINT payment_records_medical_equipment_id_fkey FOREIGN KEY (medical_equipment_id) REFERENCES public.medical_equipment(id)
);
CREATE TABLE public.vendor (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  name text NOT NULL,
  en_description text NOT NULL,
  id_description text NOT NULL,
  category text NOT NULL,
  location_map text,
  specialist jsonb,
  logo text,
  highlight_image text NOT NULL,
  reference_image ARRAY,
  CONSTRAINT vendor_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wellness (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  slug text NOT NULL,
  en_title text NOT NULL,
  id_title text NOT NULL,
  en_tagline text NOT NULL,
  id_tagline text NOT NULL,
  highlight_image text NOT NULL,
  reference_image ARRAY,
  duration_by_day integer NOT NULL,
  duration_by_night integer,
  spesific_gender USER-DEFINED NOT NULL,
  en_wellness_package_content text NOT NULL,
  id_wellness_package_content text NOT NULL,
  included jsonb,
  hotel_id uuid NOT NULL,
  real_price text NOT NULL,
  discount_price text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::status_content,
  CONSTRAINT wellness_pkey PRIMARY KEY (id),
  CONSTRAINT wellness_list_vendor_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.vendor(id),
  CONSTRAINT wellness_list_id_fkey FOREIGN KEY (id) REFERENCES public.hotel(id)
);